version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tarea-db 
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
     - '5433:5432'  
volumes:
  postgres: 